export enum CommonGatewayEvents {
    Error = 'error',
    Validate = 'validate',
    ValidateACK = 'validateWithAck',
    BroadcastAll = 'broadcastAll',
    JoinRoom = 'joinRoom',
    RoomAssigned = 'roomAssigned',
    RoomMessage = 'roomMessage',
    WordValidated = 'wordValidated',
    MassMessage = 'massMessage',
    Hello = 'hello',
    Clock = 'clock',
    SeeCurrentRooms = 'seeCurrentRooms',
    CurrentRooms = 'currentRooms',
    ChatHistory = 'chatHistory',    
}

export enum LobbyGatewayEvents {
    LobbyLockChanged = 'lobbyLockChanged',
    ToggleLockLobby = 'toggleLockLobby',
    StartGame = 'startGame',
    ErrorLobby = 'errorLobby',
    JoinLobby = 'joinLobby',
    PlayerJoined = 'playerJoined',
    CreateRoom = 'createRoom',
    FinishChampionSelection = 'finishChampionSelection',
    ChampSelectSubmitted = 'champSelectSubmitted',
    SubmitChampSelect = 'submitChampSelect',
    LeaderLeft = 'leaderLeft',
    PlayerLeft = 'playerLeft',
    LeaveLobby = 'leaveLobby',
    ChampSelectError = 'champSelectError',
    IsLobbyFull = 'isLobbyFull',
    IsLobbyLocked = 'isLobbyLocked',
    ChampionSelected = 'championSelected',
    ChampionDeselected = 'championDeselected',
    GetSelectedChampions = 'getSelectedChampions',
    KickPlayer = 'kickPlayer',
    Kicked = 'Kicked',
    AddBot = 'addBot',
    BotAdded = 'botAdded',
}

export enum GameGatewayEvents {
    CreateGame = 'createGame',
    GetPlayers = 'getPlayers',
    GetMapId = 'getMapId',
    UpdatePlayerStats = 'updatePlayerStats',
    PlayerStatsUpdated = 'playerStatsUpdated',
    StartCombat = 'startCombat',
    PlayerAttack = 'playerAttack',
    PlayerAttackResult = 'playerAttackResult',
    GetAccessibleTiles = 'getAccessibleTiles',
    TurnStart = 'turnStart',
    EndTurn = 'endTurn',
    NextTurn = 'nextTurn',
    MovePlayer = 'movePlayer',
    GetShortestPathToTile = 'getShortestPathToTile',
    LeaveGame = 'leaveGame',
    RebindSocketId = 'rebindSocketId',
    PlayersUpdated = 'playersUpdated',
    GridUpdated = 'gridUpdated',
    JoinGame = 'joinGame',
    TurnChanged = 'turnChanged',
    TimerTick = 'timerTick',
    TurnTimerPaused = 'turnTimerPaused',
    CombatTimerStart = 'combatTimerStart',
    CombatTimerTick = 'combatTimerTick',
    CombatTimerEnd = 'combatTimerEnd',
    EndCombat = 'endCombat',
    PauseTurnTimer = 'pauseTurnTimer',
    ResumeTurnTimer = 'resumeTurnTimer',
    FightWon = 'fightWon',
    TurnTransition = 'turnTransition',
    LastPlayerConnected = 'lastPlayerConnected',
    CombatStarted = 'combatStarted',
    UseDoor = 'useDoor',
    BreakWall = 'breakWall',
    CombatEnded = 'combatEnded',
    PlayerAttacked = 'playerAttacked',
    CombatTurnChanged = 'combatTurnChanged',
    ToggleDebug = 'toggleDebug',
    DeactivateDebug = 'deactivateDebug',
    AttemptEscape = 'attemptEscape',
    PlayerEscaped = 'playerEscaped',
    PlayerWonGame = 'playerWonGame',
    ExecuteAutoAttack = 'executeAutoAttack',
    MakePlayerLoseCombat = 'makePlayerLoseCombat',
    PlayerLostCombat = 'playerLostCombat',
    OpponentDisconnected = 'opponentDisconnected',



    BotTurn = 'botTurn',
    BotStartCombat = 'botStartCombat',
    BotAttack = 'botAttack',
    GetItems = 'getItems',
    PickupItem = 'pickupItem',
    InventoryFull = 'inventoryFull',
    DropItem = 'dropItem',
    UpdateItems = 'updateItems',
    TeamWon = 'teamWon',
}

export enum ActionJournalEvents {
    InitialTurn = 'initialTurn',
    CombatJournal = 'combatJournal',
    CombatJournalEnded = 'combatJournalEnded',
    TurnJournalTransition = 'turnJournalTransition',
    ToggleDebugJournal = 'toggleDebugJournal',
    LeaveGameJournal = 'leaveGameJournal',
    DoorToggleJournal = 'doorToggleJournal',
    CombatEscapeAttemptJournal = 'combatEscapeAttemptJournal',
    CombatEscapeAttemptJournalFailed = 'combatEscapeAttemptJournalFailed',
    AttackJournalResult = 'attackJournalResult',
    ItemPickedUp = 'itemPickedUp',
}
