import { Teams } from '../game/game-enums';
import { Player } from './player';

export const mockPlayers: Player[] = [
    {
        _id: 'player1',
        name: 'Player 1',
        championName: 'beast',
        healthPower: 6,
        maxHealthPower: 6,
        attackPower: 4,
        defensePower: 6,
        speed: 6,
        actionPoints: 1,
        maxActionPoints: 1,
        position: { x: 0, y: 0 },
        spawnPointPosition: { x: 0, y: 0 },
        isWinner: false,
        isBot: false,
        isAggressive: false,
        isLeader: true,
        isTurn: false,
        nbFightsWon: 0,
        isConnected: true,
        isCombatTurn: false,
        escapesAttempts: 0,
        maxSpeed: 6,
        team: Teams.None,
        hasFlag: false,
        items: [],
        buffs: { attackBuff: 0, defenseBuff: 0 },
        activeBuffs: [],
        isInCombat: false,
    },
    {
        _id: 'player2',
        name: 'Player 2',
        championName: 'Champion2',
        healthPower: 4,
        maxHealthPower: 4,
        attackPower: 6,
        defensePower: 4,
        speed: 6,
        actionPoints: 1,
        maxActionPoints: 1,
        position: { x: 1, y: 0 },
        spawnPointPosition: { x: 1, y: 0 },
        isWinner: false,
        isBot: false,
        isAggressive: false,
        isLeader: false,
        isTurn: false,
        nbFightsWon: 0,
        isConnected: true,
        isCombatTurn: false,
        escapesAttempts: 0,
        maxSpeed: 6,
        team: Teams.None,
        hasFlag: false,
        items: [],
        buffs: { attackBuff: 0, defenseBuff: 0 },
        activeBuffs: [],
        isInCombat: false,
    },
    {
        _id: 'player3',
        name: 'Player 3',
        championName: 'Champion3',
        healthPower: 4,
        maxHealthPower: 4,
        attackPower: 6,
        defensePower: 4,
        speed: 6,
        actionPoints: 1,
        maxActionPoints: 1,
        position: { x: 5, y: 5 },
        spawnPointPosition: { x: 5, y: 5 },
        isWinner: false,
        isBot: false,
        isAggressive: false,
        isLeader: false,
        isTurn: false,
        nbFightsWon: 0,
        isConnected: true,
        isCombatTurn: false,
        escapesAttempts: 0,
        maxSpeed: 6,
        team: Teams.None,
        hasFlag: false,
        items: [],
        buffs: { attackBuff: 0, defenseBuff: 0 },
        activeBuffs: [],
        isInCombat: false,
    },
];
